<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Upgrade steps for Feedback Flow.
 *
 * @package    block_feedback_tracker
 * @copyright  2026 Anderson Blaine <anderson@blaine.com.br>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */



/**
 * v1.0.0 baseline — fresh installations only.
 *
 * `db/install.xml` is the canonical schema; the install hook in
 * `db/install.php` seeds defaults. This plugin supports new
 * installations only — sites running a hypothetical prior version
 * that try to upgrade get an explicit error message asking them
 * to uninstall and reinstall on a clean database.
 *
 * If you ever need to re-add upgrade steps (e.g. a v1.x schema change),
 * the standard pattern returns: `if ($oldversion < <version_code>) {
 * ...; upgrade_block_savepoint(true, <version_code>, 'feedback_tracker'); }`.
 *
 * @param int $oldversion The currently-installed plugin version code.
 * @return bool True on success.
 * @throws upgrade_exception When an unsupported pre-v1 version is detected.
 */
function xmldb_block_feedback_tracker_upgrade($oldversion) {
    global $DB;

    $dbman = $DB->get_manager(); // Loads ddl manager and xmldb classes.
    /*
     * Fresh installs land here with $oldversion = 0 (the install hook
     * sets the version *after* this function returns). Returning true
     * for that case lets the install complete cleanly.
     *
     * Any non-zero oldversion below the v1.0.0 baseline means the site
     * previously had an older release of this plugin and is now trying
     * to upgrade across the schema reset. Block it with a clear,
     * actionable message — silent migration could lose data.
     */
    if ($oldversion > 0 && $oldversion < 2026060100) {
        throw new upgrade_exception(
            'block_feedback_tracker',
            $oldversion,
            'Upgrades from versions before 1.0.0 are not supported. '
                . 'Please uninstall the plugin (Site admin → Plugins → '
                . 'Plugins overview → Uninstall block_feedback_tracker), '
                . 'drop any remaining mdl_block_feedback_tracker_* tables '
                . 'manually if the uninstall left them behind, then '
                . 'reinstall on a clean database. Ledger data will be '
                . 'regenerated by re-enabling Process historical '
                . 'submissions in the admin settings after install.'
        );
    }

    // V1.0.1 — seeds the new score_thresholds_band setting so 1.0.0
    // installs pick up the design defaults without waiting for an admin
    // to visit the settings page. The set_config() call deliberately
    // skips set_updatedcallback (which only fires through
    // admin_setting_*::write_setting), avoiding the bootstrap-guard
    // path during upgrade.
    if ($oldversion < 2026060101) {
        if (get_config('block_feedback_tracker', 'score_thresholds_band') === false) {
            set_config('score_thresholds_band', '90,70,40', 'block_feedback_tracker');
        }
        upgrade_block_savepoint(true, 2026060101, 'feedback_tracker');
    }

    // V1.0.2 — block-view recomposition. No DB changes; the new Preact
    // components and CSS tokens ship in code only. The savepoint is here so
    // sites still get a deterministic upgrade marker.
    if ($oldversion < 2026060102) {
        upgrade_block_savepoint(true, 2026060102, 'feedback_tracker');
    }

    // V1.0.3 — payload extensions (perceived / paused / peer). No schema
    // changes: perceived_median_hours aliases median_raw_h, paused aggregates
    // are computed at read time from cday + cpause, peer benchmarks come from
    // the existing _group rollup. Bump calver so MUC keys roll over and
    // cached payloads pick up the new keys on first access.
    if ($oldversion < 2026060103) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060103, 'feedback_tracker');
    }

    // V1.0.4 — pending report page redesign. No DB changes; new Preact
    // components + bootstrap shape extension only. Savepoint here for the
    // upgrade marker, no cache bump (read-side payload shape unchanged).
    if ($oldversion < 2026060104) {
        upgrade_block_savepoint(true, 2026060104, 'feedback_tracker');
    }

    // V1.0.5 — dashboard redesign + new get_insights WS. The WS slots
    // into the existing dashboard cache; bump calver so per-user cached
    // dashboards re-fetch and pick up the new score_band / trend_series
    // / perceived_median_hours fields from get_dashboard.
    if ($oldversion < 2026060105) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060105, 'feedback_tracker');
    }

    // V1.0.6 — web-service completion. Five new JS write wrappers
    // (savePauseWindow / deletePauseWindow / saveCalendarDay /
    // bulkImportCalendar / saveBusinessHours), one new read WS
    // (get_audit_log, gated by the existing viewaudit capability), and a
    // drift-check phpunit test. No DB changes; no cache bump (read-side
    // payload shape unchanged).
    if ($oldversion < 2026060106) {
        upgrade_block_savepoint(true, 2026060106, 'feedback_tracker');
    }

    // V1.0.7 — trend-term refinements (adaptive w_trend + dashboard
    // momentum). No DB changes. Existing rollup rows still have
    // comp_trend = 0.5 from prior versions; they'll converge to null on
    // the natural recompute cycle (event observers / drain queue) and
    // don't need a forced recompute here.
    if ($oldversion < 2026060107) {
        upgrade_block_savepoint(true, 2026060107, 'feedback_tracker');
    }

    // V1.0.8 — combined hero+insights collapse state persisted via the
    // core user-preferences API. No schema change; the preference key
    // (block_feedback_tracker_dashboard_collapsed) is declared in
    // lib.php::block_feedback_tracker_user_preferences() and gets a
    // server-side default of '0' so existing users see the expanded
    // hero on first visit after upgrade.
    if ($oldversion < 2026060108) {
        upgrade_block_savepoint(true, 2026060108, 'feedback_tracker');
    }

    // V1.0.9 — sub-day optional event windows. Two nullable columns
    // on {block_feedback_tracker_cday} for minutes-since-midnight
    // start / end. Both null = legacy full-day rule (existing rows are
    // unaffected). Calver bump invalidates cached payloads so the new
    // paused_events_30d sidecar shows up on next read.
    if ($oldversion < 2026060109) {
        $table = new xmldb_table('block_feedback_tracker_cday');

        $field = new xmldb_field(
            'starttime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'daytype'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'endtime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'starttime'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060109, 'feedback_tracker');
    }

    // V1.0.10 — patch the PHP 8.x "implicit float→int" deprecation in
    // paused_aggregator::ymd_in_pause_span. Code-only fix, no schema or
    // cache impact — the savepoint exists for the upgrade marker so any
    // sites that picked up 1.0.9 on PHP 8.1+ converge cleanly to 1.0.10
    // with the deprecation gone.
    if ($oldversion < 2026060110) {
        upgrade_block_savepoint(true, 2026060110, 'feedback_tracker');
    }

    // V1.0.11 — UX patch: event time + date in PausedCallout, event
    // sidecar surfaced in block PausedNote, "Recent event" chip on the
    // teacher dashboard. JS-only and lang-strings — no DB or cache
    // impact. Savepoint here for the upgrade marker.
    if ($oldversion < 2026060111) {
        upgrade_block_savepoint(true, 2026060111, 'feedback_tracker');
    }

    // V1.0.12 — only genuinely "submitted" work counts toward the SLA. Every
    // rollup / pending / score query now filters submissionstatus = 'submitted'
    // (draft / new / reopened attempts are awaiting the student, not the
    // teacher). Existing ledger rows already store the correct status, so no
    // row migration is needed — but the derived per-(course, group) rollups
    // were computed under the old "count every ungraded row" rule and must be
    // rebuilt. Re-enqueue every distinct tuple so the drain_queue task
    // recomputes each rollup submitted-only on the next cron run. (Daily site
    // + trend tables self-heal on their own scheduled recompute.)
    if ($oldversion < 2026060112) {
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();
        upgrade_block_savepoint(true, 2026060112, 'feedback_tracker');
    }

    // V1.0.19 — headline "effective / perceived" times now include currently
    // pending (ungraded) work so the dashboard reflects the live backlog
    // instead of reading ~0 when little has been graded. Two new rollup
    // columns hold the include-pending medians; the score still uses the
    // graded-only median_eff_h, so it is unaffected. Re-enqueue every tuple so
    // drain_queue backfills the new columns on the next cron run.
    if ($oldversion < 2026060119) {
        $table = new xmldb_table('block_feedback_tracker_group');

        $field = new xmldb_field(
            'cur_median_eff_h',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'max_eff_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'cur_median_raw_h',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_eff_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060119, 'feedback_tracker');
    }

    if ($oldversion < 2026060129) {
        $table = new xmldb_table('block_feedback_tracker_group');

        $field = new xmldb_field(
            'cur_median_eff_days',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_raw_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'cur_median_perc_days',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_eff_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Re-enqueue every (course, group) so the new date-based day medians
        // populate on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060129, 'feedback_tracker');
    }

    if ($oldversion < 2026060131) {
        // Per-submission elapsed business days — drives banding when the
        // business-days display unit is active.
        $table = new xmldb_table('block_feedback_tracker_sub');
        $field = new xmldb_field(
            'effectivedays',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'effectivehours'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Day-ruler twins of the rollup's critical/overgoal pending counts.
        $table = new xmldb_table('block_feedback_tracker_group');
        $field = new xmldb_field(
            'critical_days',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'cur_median_perc_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }
        $field = new xmldb_field(
            'overgoal_days',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'critical_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // The per-row effectivedays column is filled lazily by the
        // backfill_effectivedays scheduled task (armed by the 2026060132
        // step below), not in-line here: a synchronous walk over the entire
        // ledger made this upgrade pathologically slow on large sites. The
        // dashboard day-ruler columns don't wait on it — rollup_service
        // recomputes day counts from timestamps on demand, and the
        // re-enqueue below refreshes every tuple on the next drain.

        // Re-enqueue every (course, group) so the new day-ruler counts
        // populate on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060131, 'feedback_tracker');
    }

    // V1.0.32 — the per-row effectivedays backfill that previously ran
    // in-line in the 2026060131 step is replaced by the
    // backfill_effectivedays scheduled task. This step only "arms" that
    // task by setting its done flag to 0 and resetting its keyset cursor;
    // the task then fills the column in time-capped, set-based batches off
    // the upgrade critical path. Sites that already completed the old
    // in-line backfill arm here too, but the task finds no NULL rows past
    // its cursor and marks itself done on the first tick.
    if ($oldversion < 2026060132) {
        set_config('effectivedays_backfill_done', '0', 'block_feedback_tracker');
        set_config('effectivedays_backfill_lastid', '0', 'block_feedback_tracker');
        upgrade_block_savepoint(true, 2026060132, 'feedback_tracker');
    }

    // V1.0.33 — display-only business-days SLA compliance. The new rollup
    // column compliance_pct_days holds the share of last-window graded
    // submissions returned within the business-days SLA goal (the new
    // sla_goal_days setting). It is the day-ruler twin of compliance_pct and,
    // like the other day twins, is display-only: the score keeps using the
    // effective-hours compliance, so switching the display unit never moves
    // the score. Seed the setting default, add the column, bump calver, and
    // re-enqueue every tuple so drain_queue backfills the column next cron run.
    if ($oldversion < 2026060133) {
        if (get_config('block_feedback_tracker', 'sla_goal_days') === false) {
            set_config('sla_goal_days', '2', 'block_feedback_tracker');
        }

        $table = new xmldb_table('block_feedback_tracker_group');
        $field = new xmldb_field(
            'compliance_pct_days',
            XMLDB_TYPE_NUMBER,
            '5, 2',
            null,
            null,
            null,
            null,
            'overgoal_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Re-enqueue every (course, group) so the new compliance_pct_days
        // column populates on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060133, 'feedback_tracker');
    }

    /* v1.0.37 — measurement cycles, latest-attempt gating and marking-workflow
     * awareness. A student who re-saves an already-marked submission used to
     * un-grade the ledger row, destroying the recorded response time; the row
     * now opens a new cycle and the closed one keeps its measurement. Eight
     * new columns support that plus core's latest-attempt gate and the
     * release clock. Existing rows are seeded conservatively so no displayed
     * number moves on upgrade. */
    if ($oldversion < 2026080202) {
        $table = new xmldb_table('block_feedback_tracker_sub');

        $fields = [
            new xmldb_field('cycle', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'attemptnumber'),
            new xmldb_field('timemarked', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timegraded'),
            new xmldb_field('timereleased', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timemarked'),
            new xmldb_field('timeclosed', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timereleased'),
            new xmldb_field('islatest', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '1', 'timeclosed'),
            new xmldb_field('iscurrent', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '1', 'islatest'),
            new xmldb_field('gradestate', XMLDB_TYPE_CHAR, '20', null, null, null, null, 'iscurrent'),
            new xmldb_field('teamgroupid', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'gradestate'),
            new xmldb_field('timeallocated', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'teamgroupid'),
            new xmldb_field('timeallocmarker', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timeallocated'),
            new xmldb_field('allocmarkerid', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'timeallocmarker'),
            new xmldb_field('allocsource', XMLDB_TYPE_CHAR, '12', null, null, null, null, 'allocmarkerid'),
        ];
        foreach ($fields as $field) {
            if (!$dbman->field_exists($table, $field)) {
                $dbman->add_field($table, $field);
            }
        }

        /* Seed timemarked and timeclosed from the existing timegraded. Every
         * pre-1.0.37 row was written by the old predicate, which only ever set
         * timegraded for a mark that postdated the hand-in — exactly the
         * condition timemarked encodes — and no site had the release clock, so
         * timeclosed equals timegraded for all of them. This keeps every
         * displayed number identical across the upgrade and gives the
         * resubmission detector a reference on day one. */
        $DB->execute(
            'UPDATE {block_feedback_tracker_sub}
                SET timemarked = timegraded, timeclosed = timegraded
              WHERE timegraded IS NOT NULL AND timemarked IS NULL'
        );

        $dropindexes = [
            new xmldb_index('uq_cm_user_attempt', XMLDB_INDEX_UNIQUE, ['cmid', 'userid', 'attemptnumber']),
        ];
        foreach ($dropindexes as $index) {
            if ($dbman->index_exists($table, $index)) {
                $dbman->drop_index($table, $index);
            }
        }

        $addindexes = [
            new xmldb_index('uq_cm_user_att_cycle', XMLDB_INDEX_UNIQUE, ['cmid', 'userid', 'attemptnumber', 'cycle']),
            new xmldb_index(
                'idx_status_cur_graded',
                XMLDB_INDEX_NOTUNIQUE,
                ['submissionstatus', 'islatest', 'iscurrent', 'timegraded']
            ),
            new xmldb_index('idx_item_user', XMLDB_INDEX_NOTUNIQUE, ['iteminstance', 'userid']),
        ];
        foreach ($addindexes as $index) {
            if (!$dbman->index_exists($table, $index)) {
                $dbman->add_index($table, $index);
            }
        }

        /* Drop the phantom rows the old code wrote for team submissions.
         * mod_assign stores a team's work in one {assign_submission} row with
         * userid = 0, which the observer mirrored verbatim: the resulting
         * ledger row was counted by the rollup (no user join) but invisible in
         * every list (which does join {user}), so it was a pending item nobody
         * could ever clear. */
        $tuples = $DB->get_records_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub} WHERE userid = 0'
        );
        $DB->delete_records_select('block_feedback_tracker_sub', 'userid = 0');
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }

        upgrade_block_savepoint(true, 2026080202, 'feedback_tracker');
    }

    /* v1.0.38 — split the response measurement into the coordination queue
     * (hand-in to allocation) and the marker turnaround (allocation to
     * grading), so a marker who inherited a long-queued submission is not
     * measured against a delay they did not cause. Purely additive: the
     * student-experience clock that feeds the score is untouched. */
    if ($oldversion < 2026080300) {
        $subtable = new xmldb_table('block_feedback_tracker_sub');
        $subfields = [
            new xmldb_field('queuehours', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'allocsource'),
            new xmldb_field('allochours', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'queuehours'),
            new xmldb_field('allocdays', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'allochours'),
            new xmldb_field('allocbucket', XMLDB_TYPE_CHAR, '10', null, null, null, null, 'allocdays'),
        ];
        foreach ($subfields as $field) {
            if (!$dbman->field_exists($subtable, $field)) {
                $dbman->add_field($subtable, $field);
            }
        }

        $grouptable = new xmldb_table('block_feedback_tracker_group');
        $groupfields = [
            new xmldb_field('unallocated', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'lastpause_reason'),
            new xmldb_field('median_queue_h', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'unallocated'),
            new xmldb_field('median_alloc_h', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'median_queue_h'),
            new xmldb_field('alloc_coverage_pct', XMLDB_TYPE_NUMBER, '5, 2', null, null, null, null, 'median_alloc_h'),
        ];
        foreach ($groupfields as $field) {
            if (!$dbman->field_exists($grouptable, $field)) {
                $dbman->add_field($grouptable, $field);
            }
        }

        /* The rollup is materialised, so every new column reads NULL until a
         * recompute runs. Re-enqueue every tuple rather than leaving the
         * dashboard showing blanks until something else happens to dirty it. */
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_BULK
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026080300, 'feedback_tracker');
    }

    /* An index leading with userid. The two user-scoped deletions added with
     * the enrolment and account-deletion observers filter on userid alone (or
     * on courseid + userid), and no existing index leads with it — the closest,
     * idx_item_user, leads with iteminstance — so both were full table scans on
     * exactly the bulk paths that matter: an end-of-term unenrolment sweep and
     * a bulk account deletion. */
    if ($oldversion < 2026080306) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $index = new xmldb_index('idx_user', XMLDB_INDEX_NOTUNIQUE, ['userid']);
        if (!$dbman->index_exists($table, $index)) {
            $dbman->add_index($table, $index);
        }

        upgrade_block_savepoint(true, 2026080306, 'feedback_tracker');
    }

    /* The gradebook becomes a second source of the student's response clock.
     * closedsource records which surface closed a cycle; gradehidden discloses
     * a grade the gradebook is keeping from the student. Both are additive and
     * both are backfilled lazily: existing closed rows were all closed from the
     * activity, so they are stamped accordingly in one statement, and the
     * gradebook is only consulted when a row is next re-derived. No stored
     * response time moves — the new source can only ever supply an EARLIER
     * instant for a cycle that had none. */
    if ($oldversion < 2026080400) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $fields = [
            new xmldb_field('closedsource', XMLDB_TYPE_CHAR, '10', null, null, null, null, 'timeclosed'),
            new xmldb_field('gradehidden', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'closedsource'),
        ];
        foreach ($fields as $field) {
            if (!$dbman->field_exists($table, $field)) {
                $dbman->add_field($table, $field);
            }
        }

        $DB->execute(
            "UPDATE {block_feedback_tracker_sub}
                SET closedsource = :src
              WHERE timeclosed IS NOT NULL AND closedsource IS NULL",
            ['src' => \block_feedback_tracker\local\sla\gradebook_response::SOURCE_ASSIGN]
        );

        upgrade_block_savepoint(true, 2026080400, 'feedback_tracker');
    }

    return true;
}
