<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Upgrade steps for Feedback Flow.
 *
 * @package    block_feedback_tracker
 * @copyright  2026 Anderson Blaine <anderson@blaine.com.br>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */



/**
 * Upgrade steps for block_feedback_tracker.
 *
 * Upgrades are supported from 1.0.0 (2026060100) onwards. A site on an
 * older release gets an explicit error asking it to uninstall and reinstall
 * on a clean database, because 1.0.0 reset the schema.
 *
 * @param int $oldversion The currently-installed plugin version code.
 * @return bool True on success.
 * @throws upgrade_exception When an unsupported pre-v1 version is detected.
 */
function xmldb_block_feedback_tracker_upgrade($oldversion) {
    global $DB;

    $dbman = $DB->get_manager(); // Loads ddl manager and xmldb classes.
    /*
     * Moodle never calls this on a fresh install (install.xml and
     * db/install.php run instead). A version below the 1.0.0 baseline is an
     * older release upgrading across the schema reset: refuse it with an
     * actionable message, because a silent migration could lose data.
     */
    if ($oldversion > 0 && $oldversion < 2026060100) {
        throw new upgrade_exception(
            'block_feedback_tracker',
            $oldversion,
            'Upgrades from versions before 1.0.0 are not supported. '
                . 'Please uninstall the plugin (Site admin → Plugins → '
                . 'Plugins overview → Uninstall block_feedback_tracker), '
                . 'drop any remaining mdl_block_feedback_tracker_* tables '
                . 'manually if the uninstall left them behind, then '
                . 'reinstall on a clean database. Ledger data will be '
                . 'regenerated by re-enabling Process historical '
                . 'submissions in the admin settings after install.'
        );
    }

    // Seed the new score_thresholds_band setting so existing installs get the
    // default before an admin saves the settings page. set_config() fires no
    // set_updatedcallback, so the rollup invalidation does not run mid-upgrade.
    if ($oldversion < 2026060101) {
        if (get_config('block_feedback_tracker', 'score_thresholds_band') === false) {
            set_config('score_thresholds_band', '90,70,40', 'block_feedback_tracker');
        }
        upgrade_block_savepoint(true, 2026060101, 'feedback_tracker');
    }

    // Savepoint only: code-only release.
    if ($oldversion < 2026060102) {
        upgrade_block_savepoint(true, 2026060102, 'feedback_tracker');
    }

    // The payload gained perceived / paused / peer fields (no schema change).
    // Bump calver so the calver-keyed payload caches roll over.
    if ($oldversion < 2026060103) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060103, 'feedback_tracker');
    }

    // Savepoint only: code-only release, cached payload shape unchanged.
    if ($oldversion < 2026060104) {
        upgrade_block_savepoint(true, 2026060104, 'feedback_tracker');
    }

    // The get_dashboard payload gained score_band / trend_series /
    // perceived_median_hours, and get_insights shares its cache: bump calver so
    // cached dashboards roll over.
    if ($oldversion < 2026060105) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060105, 'feedback_tracker');
    }

    // Savepoint only; the version bump installs the new get_audit_log web service.
    if ($oldversion < 2026060106) {
        upgrade_block_savepoint(true, 2026060106, 'feedback_tracker');
    }

    // Savepoint only. Rollup rows holding a comp_trend from the old formula are
    // rewritten on their next ordinary recompute, so none is forced here.
    if ($oldversion < 2026060107) {
        upgrade_block_savepoint(true, 2026060107, 'feedback_tracker');
    }

    // Savepoint only: the new dashboard_collapsed user preference defaults to
    // '0' (expanded); see block_feedback_tracker_user_preferences().
    if ($oldversion < 2026060108) {
        upgrade_block_savepoint(true, 2026060108, 'feedback_tracker');
    }

    // Sub-day optional event windows: nullable start / end in minutes since
    // midnight on {block_feedback_tracker_cday}. Both null keeps the full-day
    // rule, so existing rows are unaffected. The calver bump rolls over cached
    // payloads so the new paused_events_30d field appears.
    if ($oldversion < 2026060109) {
        $table = new xmldb_table('block_feedback_tracker_cday');

        $field = new xmldb_field(
            'starttime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'daytype'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'endtime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'starttime'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060109, 'feedback_tracker');
    }

    // Savepoint only: code-only release.
    if ($oldversion < 2026060110) {
        upgrade_block_savepoint(true, 2026060110, 'feedback_tracker');
    }

    // Savepoint only: code-only release.
    if ($oldversion < 2026060111) {
        upgrade_block_savepoint(true, 2026060111, 'feedback_tracker');
    }

    // Only submitted work counts toward the SLA now. Ledger rows already store
    // their status, but the rollups were computed counting every ungraded row:
    // re-enqueue every (course, group) so drain_queue rebuilds them. The daily
    // site and trend tables catch up on their own scheduled recompute.
    if ($oldversion < 2026060112) {
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();
        upgrade_block_savepoint(true, 2026060112, 'feedback_tracker');
    }

    // Headline medians that include pending work (cur_median_eff_h / _raw_h);
    // the score keeps the graded-only median_eff_h. Re-enqueue every
    // (course, group) so drain_queue fills the new columns.
    if ($oldversion < 2026060119) {
        $table = new xmldb_table('block_feedback_tracker_group');

        $field = new xmldb_field(
            'cur_median_eff_h',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'max_eff_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'cur_median_raw_h',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_eff_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060119, 'feedback_tracker');
    }

    if ($oldversion < 2026060129) {
        $table = new xmldb_table('block_feedback_tracker_group');

        $field = new xmldb_field(
            'cur_median_eff_days',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_raw_h'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'cur_median_perc_days',
            XMLDB_TYPE_NUMBER,
            '10, 2',
            null,
            null,
            null,
            null,
            'cur_median_eff_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Re-enqueue every (course, group) so the new date-based day medians
        // populate on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060129, 'feedback_tracker');
    }

    if ($oldversion < 2026060131) {
        // Per-submission elapsed business days — drives banding when the
        // business-days display unit is active.
        $table = new xmldb_table('block_feedback_tracker_sub');
        $field = new xmldb_field(
            'effectivedays',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'effectivehours'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Day-ruler twins of the rollup's critical/overgoal pending counts.
        $table = new xmldb_table('block_feedback_tracker_group');
        $field = new xmldb_field(
            'critical_days',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'cur_median_perc_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }
        $field = new xmldb_field(
            'overgoal_days',
            XMLDB_TYPE_INTEGER,
            '10',
            null,
            null,
            null,
            null,
            'critical_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // The per-row effectivedays column is filled by the
        // backfill_effectivedays scheduled task (armed by the 2026060132 step
        // below), not here: walking the whole ledger inside the upgrade is too
        // slow on a large site. The rollup's day counts do not wait for it;
        // rollup_service derives them from timestamps.

        // Re-enqueue every (course, group) so the new day-ruler counts
        // populate on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026060131, 'feedback_tracker');
    }

    // Arm the backfill_effectivedays task (done flag 0, keyset cursor 0); it
    // fills effectivedays in time-capped batches off the upgrade path. Where
    // the column is already filled, the task finds no NULL rows and marks
    // itself done on its first tick.
    if ($oldversion < 2026060132) {
        set_config('effectivedays_backfill_done', '0', 'block_feedback_tracker');
        set_config('effectivedays_backfill_lastid', '0', 'block_feedback_tracker');
        upgrade_block_savepoint(true, 2026060132, 'feedback_tracker');
    }

    // Display-only business-days compliance: compliance_pct_days is the
    // day-ruler twin of compliance_pct, measured against the new sla_goal_days
    // setting; the score keeps the effective-hours compliance. Seed the
    // setting, add the column, re-enqueue every (course, group) so drain_queue
    // fills it, and bump calver.
    if ($oldversion < 2026060133) {
        if (get_config('block_feedback_tracker', 'sla_goal_days') === false) {
            set_config('sla_goal_days', '2', 'block_feedback_tracker');
        }

        $table = new xmldb_table('block_feedback_tracker_group');
        $field = new xmldb_field(
            'compliance_pct_days',
            XMLDB_TYPE_NUMBER,
            '5, 2',
            null,
            null,
            null,
            null,
            'overgoal_days'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Re-enqueue every (course, group) so the new compliance_pct_days
        // column populates on the next drain.
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }
        $tuples->close();

        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060133, 'feedback_tracker');
    }

    /* Measurement cycles, latest-attempt gating, the marking-workflow release
     * clock and marker allocation. Re-saving an already-marked submission opens
     * a new cycle instead of reopening the closed one, so a recorded response
     * time is never destroyed. Existing rows are seeded so no displayed number
     * moves on upgrade. */
    if ($oldversion < 2026080202) {
        $table = new xmldb_table('block_feedback_tracker_sub');

        $fields = [
            new xmldb_field('cycle', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'attemptnumber'),
            new xmldb_field('timemarked', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timegraded'),
            new xmldb_field('timereleased', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timemarked'),
            new xmldb_field('timeclosed', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timereleased'),
            new xmldb_field('islatest', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '1', 'timeclosed'),
            new xmldb_field('iscurrent', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '1', 'islatest'),
            new xmldb_field('gradestate', XMLDB_TYPE_CHAR, '20', null, null, null, null, 'iscurrent'),
            new xmldb_field('teamgroupid', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'gradestate'),
            new xmldb_field('timeallocated', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'teamgroupid'),
            new xmldb_field('timeallocmarker', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'timeallocated'),
            new xmldb_field('allocmarkerid', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'timeallocmarker'),
            new xmldb_field('allocsource', XMLDB_TYPE_CHAR, '12', null, null, null, null, 'allocmarkerid'),
        ];
        foreach ($fields as $field) {
            if (!$dbman->field_exists($table, $field)) {
                $dbman->add_field($table, $field);
            }
        }

        /* Seed timemarked and timeclosed from timegraded. Rows written before
         * this version set timegraded only for a mark that postdated the
         * hand-in, which is exactly what timemarked encodes, and none had the
         * release clock, so timeclosed equals timegraded for all of them. Every
         * displayed number stays the same and the resubmission detector has a
         * reference from the start. */
        $DB->execute(
            'UPDATE {block_feedback_tracker_sub}
                SET timemarked = timegraded, timeclosed = timegraded
              WHERE timegraded IS NOT NULL AND timemarked IS NULL'
        );

        $dropindexes = [
            new xmldb_index('uq_cm_user_attempt', XMLDB_INDEX_UNIQUE, ['cmid', 'userid', 'attemptnumber']),
        ];
        foreach ($dropindexes as $index) {
            if ($dbman->index_exists($table, $index)) {
                $dbman->drop_index($table, $index);
            }
        }

        $addindexes = [
            new xmldb_index('uq_cm_user_att_cycle', XMLDB_INDEX_UNIQUE, ['cmid', 'userid', 'attemptnumber', 'cycle']),
            new xmldb_index(
                'idx_status_cur_graded',
                XMLDB_INDEX_NOTUNIQUE,
                ['submissionstatus', 'islatest', 'iscurrent', 'timegraded']
            ),
            new xmldb_index('idx_item_user', XMLDB_INDEX_NOTUNIQUE, ['iteminstance', 'userid']),
        ];
        foreach ($addindexes as $index) {
            if (!$dbman->index_exists($table, $index)) {
                $dbman->add_index($table, $index);
            }
        }

        /* Drop the userid = 0 rows earlier versions mirrored from team
         * submissions (mod_assign keeps a team's work in one {assign_submission}
         * row with userid = 0). The rollup counted them but every list joins
         * {user} and hid them, so they were pending items nobody could clear. */
        $tuples = $DB->get_records_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub} WHERE userid = 0'
        );
        $DB->delete_records_select('block_feedback_tracker_sub', 'userid = 0');
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_SUBMISSION
            );
        }

        upgrade_block_savepoint(true, 2026080202, 'feedback_tracker');
    }

    /* Split the response measurement into the coordination queue (hand-in to
     * allocation) and the marker turnaround (allocation to grading), so a
     * marker who inherited a long-queued submission is not measured against a
     * delay they did not cause. Purely additive: the student-experience clock
     * that feeds the score is untouched. */
    if ($oldversion < 2026080300) {
        $subtable = new xmldb_table('block_feedback_tracker_sub');
        $subfields = [
            new xmldb_field('queuehours', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'allocsource'),
            new xmldb_field('allochours', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'queuehours'),
            new xmldb_field('allocdays', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'allochours'),
            new xmldb_field('allocbucket', XMLDB_TYPE_CHAR, '10', null, null, null, null, 'allocdays'),
        ];
        foreach ($subfields as $field) {
            if (!$dbman->field_exists($subtable, $field)) {
                $dbman->add_field($subtable, $field);
            }
        }

        $grouptable = new xmldb_table('block_feedback_tracker_group');
        $groupfields = [
            new xmldb_field('unallocated', XMLDB_TYPE_INTEGER, '10', XMLDB_UNSIGNED, null, null, null, 'lastpause_reason'),
            new xmldb_field('median_queue_h', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'unallocated'),
            new xmldb_field('median_alloc_h', XMLDB_TYPE_NUMBER, '10, 2', null, null, null, null, 'median_queue_h'),
            new xmldb_field('alloc_coverage_pct', XMLDB_TYPE_NUMBER, '5, 2', null, null, null, null, 'median_alloc_h'),
        ];
        foreach ($groupfields as $field) {
            if (!$dbman->field_exists($grouptable, $field)) {
                $dbman->add_field($grouptable, $field);
            }
        }

        /* The rollup is materialised, so every new column reads NULL until a
         * recompute runs. Re-enqueue every tuple rather than leaving the
         * dashboard showing blanks until something else happens to dirty it. */
        $tuples = $DB->get_recordset_sql(
            'SELECT DISTINCT courseid, groupid FROM {block_feedback_tracker_sub}'
        );
        foreach ($tuples as $t) {
            \block_feedback_tracker\local\sla\dirty_queue::enqueue(
                (int) $t->courseid,
                (int) $t->groupid,
                \block_feedback_tracker\local\sla\dirty_queue::REASON_BULK
            );
        }
        $tuples->close();

        upgrade_block_savepoint(true, 2026080300, 'feedback_tracker');
    }

    /* An index leading with userid. The deletions run by the enrolment and
     * account-deletion observers filter on userid alone (or courseid + userid),
     * and no other index leads with it (idx_item_user leads with iteminstance),
     * so without it both scan the whole table on the bulk paths: an end-of-term
     * unenrolment and a bulk account deletion. */
    if ($oldversion < 2026080306) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $index = new xmldb_index('idx_user', XMLDB_INDEX_NOTUNIQUE, ['userid']);
        if (!$dbman->index_exists($table, $index)) {
            $dbman->add_index($table, $index);
        }

        upgrade_block_savepoint(true, 2026080306, 'feedback_tracker');
    }

    /* The gradebook becomes a second source of the student's response clock.
     * closedsource records which surface closed a cycle; gradehidden discloses
     * a grade the gradebook is keeping from the student. Both are additive and
     * both are backfilled lazily: existing closed rows were all closed from the
     * activity, so they are stamped accordingly in one statement, and the
     * gradebook is only consulted when a row is next re-derived. No stored
     * response time moves: the new source only supplies an instant for a
     * cycle that had none. */
    if ($oldversion < 2026080400) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $fields = [
            new xmldb_field('closedsource', XMLDB_TYPE_CHAR, '10', null, null, null, null, 'timeclosed'),
            new xmldb_field('gradehidden', XMLDB_TYPE_INTEGER, '1', XMLDB_UNSIGNED, XMLDB_NOTNULL, null, '0', 'closedsource'),
        ];
        foreach ($fields as $field) {
            if (!$dbman->field_exists($table, $field)) {
                $dbman->add_field($table, $field);
            }
        }

        $DB->execute(
            "UPDATE {block_feedback_tracker_sub}
                SET closedsource = :src
              WHERE timeclosed IS NOT NULL AND closedsource IS NULL",
            ['src' => \block_feedback_tracker\local\sla\gradebook_response::SOURCE_ASSIGN]
        );

        upgrade_block_savepoint(true, 2026080400, 'feedback_tracker');
    }

    /* Drop gradehidden, added by the previous step. Whether the gradebook hides
     * a grade is a live fact, not a measurement: core fires no event when a
     * grade's visibility changes, and a hide-until date expires by time alone,
     * so a stored copy drifts silently while still being exported to the data
     * subject as current. The pending report reads visibility at display time. */
    if ($oldversion < 2026080401) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $field = new xmldb_field('gradehidden');
        if ($dbman->field_exists($table, $field)) {
            $dbman->drop_field($table, $field);
        }

        upgrade_block_savepoint(true, 2026080401, 'feedback_tracker');
    }

    /* Give reconciliation its own time cap, seeded from the drain cap it used
     * to share: taking the new setting's default would silently revert a site
     * that had raised the old one for reconciliation's sake. Untouched sites
     * read 50 either way. */
    if ($oldversion < 2026081100) {
        $inherited = get_config('block_feedback_tracker', 'drain_time_cap_seconds');
        if ($inherited !== false && $inherited !== null && (string) $inherited !== '') {
            set_config('reconcile_time_cap_seconds', (string) $inherited, 'block_feedback_tracker');
        }

        upgrade_block_savepoint(true, 2026081100, 'feedback_tracker');
    }

    /* Index the reconciler's keyset sweeps. They page on `id > :cursor` while
     * filtering on courseid; with only the primary key, the course filter is a
     * residual over the id range scan, which is most of the work when the
     * tracked courses are a small slice of the ledger.
     *
     * It does not help the two row-creating sweeps: they drive from
     * {assign_submission}, which has no course column, so their keyset is over
     * a different table. */
    if ($oldversion < 2026081101) {
        $table = new xmldb_table('block_feedback_tracker_sub');
        $index = new xmldb_index('idx_course_id', XMLDB_INDEX_NOTUNIQUE, ['courseid', 'id']);
        if (!$dbman->index_exists($table, $index)) {
            $dbman->add_index($table, $index);
        }

        upgrade_block_savepoint(true, 2026081101, 'feedback_tracker');
    }

    /* The departed-participant sweep's cursor changed from an index into the
     * sorted list of processable courses to a course id. An old value would read
     * as "resume after course N" and skip every course with a lower id for the
     * whole first pass, so it is unset. */
    if ($oldversion < 2026081102) {
        unset_config('reconcile_cursor_participant', 'block_feedback_tracker');

        upgrade_block_savepoint(true, 2026081102, 'feedback_tracker');
    }

    /* Savepoint only: the reconciler pages by window now, and its cursors keep
     * their meaning, so there is nothing to migrate. */
    if ($oldversion < 2026090300) {
        upgrade_block_savepoint(true, 2026090300, 'feedback_tracker');
    }

    return true;
}
